# Config file for mpqdisk.exe
# Copyright linsmod<at>qq.com 
# github:linsmod:mpqdisk

# mpqdisk.exe --mount --config <config_file_path>
# mpqdisk.exe --mount --files war3.mpq War3Local.mpq War3x.mpq War3xlocal.mpq
# mpqdisk.exe --mount --files war3.mpq War3Local.mpq War3x.mpq War3xlocal.mpq --volume Z:
# mpqdisk.exe --mount --files war3.mpq War3Local.mpq War3x.mpq War3xlocal.mpq --volume Z: Warcraft-III-1.29.2-enUS

[mount]
# Optional: Specify the volume to mount.
# If no volume is provided, the system will automatically select an available one.
# format: `volume = label: name` (e.g., `volume = H: MyData`)
volume = Z: Warcraft-III-1.29.2-enUS

[files]
# Mount MPQ files using absolute paths or relative paths from this config file's location.
# Files are loaded in overlay (patch) mode, in the order listed.
# Priority increases from first to last.
# The last MPQ has the highest priority.
# If the same internal file exists in multiple MPQs,
# only the version from the highest-priority MPQ is visible.

war3.mpq
War3Local.mpq
War3x.mpq
War3xlocal.mpq